### Recuperar todos los usuarios
GET https://servidordsw.onrender.com/usuarios

### Recuperar un usuario por id

### Recuperar un usuario por email

### Crear un usuario con POST
POST https://servidordsw.onrender.com/usuarios
Content-Type: application/json

{
    "dni": 11222333,
    "nombre": "Rodrigo",
    "apellido": "Gimenez",
    "telefono": 99999999,
    "mail": "mail@gmail.com",
    "contraseña": "contr987",
    "rol": "user"
}

### Actualizar algo a un usuario con PATCH
PATCH https://servidordsw.onrender.com/usuarios/1
Content-Type: application/json

{
    "nombre": "Pablo"
}

### Eliminar un usuario con DELETE  
DELETE https://servidordsw.onrender.com/usuarios/7


### Recuperar todos los productos
GET https://servidordsw.onrender.com/productos

### Recuperar un producto por id
GEThttps://servidordsw.onrender.com/productos/1

### Crear un producto con POST
POST https://servidordsw.onrender.com/productos
Content-Type: application/json

{
    "nombre": "RedBull",
    "descripcion": "Bebida energetica",
    "tipo": "Bebida",
    "img": "https://images.ctfassets.net/lcr8qbvxj7mh/eyz1nHwgaDd9TKO6jslKD/1964dc02d78dc20fe267d864d5fabe14/DRES_AR_ED-250ml_cold_closed_front_redbullcom.png"
}
