### Recuperar todos los usuarios
GET http://localhost:1234/usuarios

### Recuperar un usuario por id

### Recuperar un usuario por email

### Crear un usuario con POST
POST http://localhost:1234/usuarios
Content-Type: application/json

{
    "dni": 11222333,
    "nombre": "Rodrigo",
    "apellido": "Gimenez",
    "telefono": 99999999,
    "mail": "mail@gmail.com",
    "contraseña": "contr987",
    "rol": "user"
}

### Actualizar algo a un usuario con PATCH
PATCH http://localhost:1234/usuarios/1
Content-Type: application/json

{
    "nombre": "Pablo"
}

### Eliminar un usuario con DELETE  
DELETE http://localhost:1234/usuarios/7


### Recuperar todos los productos
GET http://localhost:1234/productos

### Recuperar un producto por id
GET http://localhost:1234/productos/1

### Crear un producto con POST
POST http://localhost:1234/productos
Content-Type: application/json

{
    "nombre": "RedBull",
    "descripcion": "Bebida energetica",
    "tipo": "Bebida",
    "img": "https://images.ctfassets.net/lcr8qbvxj7mh/eyz1nHwgaDd9TKO6jslKD/1964dc02d78dc20fe267d864d5fabe14/DRES_AR_ED-250ml_cold_closed_front_redbullcom.png"
}
